#!/bin/bash
if [[ $(uname -r) =~ Microsoft$ ]]; then
    alias adb="/mnt/d/Android/android-sdk/platform-tools/adb.exe"
else
    case "$(uname -s)" in

       Darwin)
          export ANDROID_HOME=/Users/$USER/Library/Android/sdk
          export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
         ;;

       Linux)
         echo 'Linux'
         ;;

       *)
         echo 'other OS'
         ;;
    esac
fi

