#!/bin/bash
if [[ $(uname -r) =~ Microsoft$ ]]; then
    alias adb="/mnt/c/Users/yosap/AppData/Local/Android/Sdk/platform-tools/adb.exe"
else
    case "$(uname -s)" in

       Darwin)
         echo 'Mac OS X'
         ;;

       Linux)
         echo 'Linux'
         ;;

       *)
         echo 'other OS'
         ;;
    esac
fi

